name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Unit tests
      run: ./gradlew testDebugUnitTest

    - name: Create JaCoCo coverage report
      run: ./gradlew allDebugCoverage

    - name: Upload JaCoCo test report
      uses: actions/upload-artifact@v3
      with:
        name: jacocoReport
        path: build/reports/jacoco/allDebugCoverage/html

    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.2
      with:
        paths: ${{ github.workspace }}/build/reports/jacoco/allDebugCoverage/allDebugCoverage.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 30
        min-coverage-changed-files: 50

    - name: Detekt validation
      run: ./gradlew detekt
